### ISSUE TITLE
Doesn't work on Raspberry Pi 64bit

### ISSUE THREAD

**Issue by LivexMania** [hanzi/libmgba-py#5]
Hello, 
I guess the lib (especially _pylib) need to be port to linux arm64 ?
I see there is for macos arm64, but not for linux ?

it's the first time I ask something on github, so pardon me if what I'm asking is wrong.

**Comment by Portentum-V** [comment]
I think I am having a similar issue and so will add some context.

I manually built mGBA 0.10.5 before using the setup.py provided. Importing mgba.audio causes an unexpected error:
```
Python 3.13.7 (main, Sep 29 2025, 21:11:39) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mgba.audio

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import mgba.audio
  File "/home/pi/Pokemon/pokebot-gen3/mgba/__init__.py", line 6, in <module>
    from ._pylib import ffi, lib  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/pi/Pokemon/pokebot-gen3/mgba/_pylib.abi3.so: undefined symbol: EReaderScanLoadImageA
```

```
$ objdump -T mgba/_pylib.abi3.so | grep EReaderScanLoadImageA
0000000000000000      D  *UND*  0000000000000000  Base        EReaderScanLoadImageA
00000000000afc00 g    DF .text  0000000000000004  Base        _cffi_d_EReaderScanLoadImageA
00000000000f5b40 g    DF .text  0000000000000230  Base        _cffi_f_EReaderScanLoadImageA
```

**Comment by GerardOSullivan** [comment]
I don't know if it helps but this fork fixed it for me https://github.com/Alexder-13/libmgba-py-Guide-for-Raspberry-Pi/releases/tag/0.2.0-2
